// Browser encodings from Aaron’s Black Circuit pack v3.1.0; masters remain untouched.
export const AUDIO_CATALOG = [
  {
    id: "00-black-circuit",
    title: "Black Circuit",
    src: "/audio/black-circuit/music/00-black-circuit.ogg",
    gain: 0.65,
    loop: true,
    category: "music",
  },
  {
    id: "01-idle-voltage",
    title: "Idle Voltage",
    src: "/audio/black-circuit/music/01-idle-voltage.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "02-neon-branches",
    title: "Neon Branches",
    src: "/audio/black-circuit/music/02-neon-branches.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "03-cache-district",
    title: "Cache District",
    src: "/audio/black-circuit/music/03-cache-district.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "04-copper-rain",
    title: "Copper Rain",
    src: "/audio/black-circuit/music/04-copper-rain.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "05-ghost-commit",
    title: "Ghost Commit",
    src: "/audio/black-circuit/music/05-ghost-commit.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "06-night-compiler",
    title: "Night Compiler",
    src: "/audio/black-circuit/music/06-night-compiler.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "07-thread-garden",
    title: "Thread Garden",
    src: "/audio/black-circuit/music/07-thread-garden.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "08-subsurface-bus",
    title: "Subsurface Bus",
    src: "/audio/black-circuit/music/08-subsurface-bus.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "09-quiet-overclock",
    title: "Quiet Overclock",
    src: "/audio/black-circuit/music/09-quiet-overclock.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "10-memory-skyline",
    title: "Memory Skyline",
    src: "/audio/black-circuit/music/10-memory-skyline.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "11-merge-current",
    title: "Merge Current",
    src: "/audio/black-circuit/music/11-merge-current.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "12-afterimage-protocol",
    title: "Afterimage Protocol",
    src: "/audio/black-circuit/music/12-afterimage-protocol.ogg",
    gain: 0.5,
    loop: true,
    category: "music",
  },
  {
    id: "ui-click-01",
    title: "Menu click / magnetic",
    src: "/audio/black-circuit/sfx/ui-click-01.ogg",
    gain: 0.34,
    loop: false,
    category: "sfx",
  },
  {
    id: "ui-click-02",
    title: "Menu click / relay",
    src: "/audio/black-circuit/sfx/ui-click-02.ogg",
    gain: 0.34,
    loop: false,
    category: "sfx",
  },
  {
    id: "ui-click-03",
    title: "Menu click / circuit",
    src: "/audio/black-circuit/sfx/ui-click-03.ogg",
    gain: 0.34,
    loop: false,
    category: "sfx",
  },
  {
    id: "ui-hover",
    title: "Menu focus",
    src: "/audio/black-circuit/sfx/ui-hover.ogg",
    gain: 0.13,
    loop: false,
    category: "sfx",
  },
  {
    id: "ui-activate",
    title: "Menu activation",
    src: "/audio/black-circuit/sfx/ui-activate.ogg",
    gain: 0.43,
    loop: false,
    category: "sfx",
  },
  {
    id: "ui-back",
    title: "Back / cancel",
    src: "/audio/black-circuit/sfx/ui-back.ogg",
    gain: 0.3,
    loop: false,
    category: "sfx",
  },
  {
    id: "ui-unavailable",
    title: "Unavailable action",
    src: "/audio/black-circuit/sfx/ui-unavailable.ogg",
    gain: 0.23,
    loop: false,
    category: "sfx",
  },
  {
    id: "repo-city-spawn",
    title: "Repository City materializes",
    src: "/audio/black-circuit/sfx/repo-city-spawn.ogg",
    gain: 0.54,
    loop: false,
    category: "sfx",
  },
  {
    id: "repo-select-01",
    title: "Repository select / steel",
    src: "/audio/black-circuit/sfx/repo-select-01.ogg",
    gain: 0.32,
    loop: false,
    category: "sfx",
  },
  {
    id: "repo-select-02",
    title: "Repository select / carbon",
    src: "/audio/black-circuit/sfx/repo-select-02.ogg",
    gain: 0.32,
    loop: false,
    category: "sfx",
  },
  {
    id: "repo-select-03",
    title: "Repository select / flux",
    src: "/audio/black-circuit/sfx/repo-select-03.ogg",
    gain: 0.32,
    loop: false,
    category: "sfx",
  },
  {
    id: "projection-on",
    title: "Projected screen on",
    src: "/audio/black-circuit/sfx/projection-on.ogg",
    gain: 0.4,
    loop: false,
    category: "sfx",
  },
  {
    id: "projection-off",
    title: "Projected screen off",
    src: "/audio/black-circuit/sfx/projection-off.ogg",
    gain: 0.36,
    loop: false,
    category: "sfx",
  },
  {
    id: "screen-extrude-off",
    title: "3D screen returns to UI",
    src: "/audio/black-circuit/sfx/screen-extrude-off.ogg",
    gain: 0.4,
    loop: false,
    category: "sfx",
  },
  {
    id: "object-grab",
    title: "Electrical object grab",
    src: "/audio/black-circuit/sfx/object-grab.ogg",
    gain: 0.44,
    loop: false,
    category: "sfx",
  },
  {
    id: "object-hold-loop",
    title: "Electrical conduit / held object",
    src: "/audio/black-circuit/sfx/object-hold-loop.ogg",
    gain: 0.17,
    loop: true,
    category: "sfx",
  },
  {
    id: "object-drop",
    title: "Object placement / drop",
    src: "/audio/black-circuit/sfx/object-drop.ogg",
    gain: 0.44,
    loop: false,
    category: "sfx",
  },
  {
    id: "agent-activate",
    title: "Agent coding activation",
    src: "/audio/black-circuit/sfx/agent-activate.ogg",
    gain: 0.4,
    loop: false,
    category: "sfx",
  },
  {
    id: "agent-coding-loop",
    title: "Agent terminal coding",
    src: "/audio/black-circuit/sfx/agent-coding-loop.ogg",
    gain: 0.14,
    loop: true,
    category: "sfx",
  },
  {
    id: "agent-cancel",
    title: "Agent task stopped",
    src: "/audio/black-circuit/sfx/agent-cancel.ogg",
    gain: 0.3,
    loop: false,
    category: "sfx",
  },
  {
    id: "code-canopy",
    title: "Code Canopy / digital environment",
    src: "/audio/black-circuit/sfx/code-canopy.ogg",
    gain: 0.24,
    loop: true,
    category: "ambience",
  },
  {
    id: "world-jack-in",
    title: "World entry / jack in",
    src: "/audio/black-circuit/sfx/world-jack-in.ogg",
    gain: 0.62,
    loop: false,
    category: "sfx",
  },
  {
    id: "screen-extrude-on",
    title: "2D to 3D screen extrusion",
    src: "/audio/black-circuit/sfx/screen-extrude-on.ogg",
    gain: 0.44,
    loop: false,
    category: "sfx",
  },
  {
    id: "agent-complete",
    title: "Agent task complete",
    src: "/audio/black-circuit/sfx/agent-complete.ogg",
    gain: 0.43,
    loop: false,
    category: "sfx",
  },
  {
    id: "avatar-materialize",
    title: "Avatar materialization",
    src: "/audio/avatar-materialize.wav",
    gain: 0.62,
    loop: false,
    category: "sfx",
  },
  {
    id: "repo-stream-up",
    title: "Repository object stream launch",
    src: "/audio/repo-stream-up.wav",
    gain: 0.62,
    loop: false,
    category: "sfx",
  },
  {
    id: "repo-stream-in",
    title: "Repository object stream return",
    src: "/audio/repo-stream-in.wav",
    gain: 0.62,
    loop: false,
    category: "sfx",
  },
  {
    id: "repo-stream-up-collective",
    title: "Repository load collective stream launch",
    src: "/audio/repo-stream-up-collective.wav",
    gain: 0.62,
    loop: false,
    category: "sfx",
  },
  {
    id: "repo-stream-in-collective",
    title: "Repository load collective stream return",
    src: "/audio/repo-stream-in-collective.wav",
    gain: 0.62,
    loop: false,
    category: "sfx",
  },
] as const;
export type AudioCue = (typeof AUDIO_CATALOG)[number]["id"];
