"""Non-destructive v2 import. Never executes supplier scripts or modifies originals."""
import hashlib
import json
import shutil
from pathlib import Path
from PIL import Image

REPO = Path(__file__).resolve().parents[2]
VISUAL = Path('/mnt/c/Codex/3D avatars/aiw-environment-expansion-v2')
AUDIO = Path('/mnt/c/Codex/3D avatars/aiw-environment-audio-expansion-v2')
PUBLIC = REPO / 'apps/web/public'
DEST = PUBLIC / 'assets/environments/expansion-v2'
DEST.mkdir(parents=True, exist_ok=True)


def sha(p):
    return hashlib.file_digest(p.open('rb'), 'sha256').hexdigest()


inventory = []
for root in [VISUAL, AUDIO]:
    for p in sorted(root.rglob('*')):
        if p.is_file():
            inventory.append(dict(pack=root.name, path=p.relative_to(root).as_posix(), bytes=p.stat().st_size, sha256=sha(p)))

assets = []
catalog = {}
source = json.loads((VISUAL / 'manifest.json').read_text())
fx = json.loads((VISUAL / 'fx/manifest.json').read_text())


def record(src, dest, ident, operation):
    row = dict(id=ident, source={'pack': VISUAL.name if src.is_relative_to(VISUAL) else AUDIO.name,
        'path': src.relative_to(VISUAL if src.is_relative_to(VISUAL) else AUDIO).as_posix(), 'sha256': sha(src)},
        path=dest.relative_to(PUBLIC).as_posix(), bytes=dest.stat().st_size, sha256=sha(dest), operation=operation)
    if dest.suffix in ['.png', '.webp']:
        with Image.open(dest) as im:
            im.load()
            row['dimensions'] = list(im.size)
            row['mode'] = im.mode
    assets.append(row)


for a in source['assets']:
    ident = a['id']
    concept = ident.startswith('prop_')
    src = VISUAL / ('concepts/' + ident + '.png' if concept else a['paths']['runtime'])
    role = 'prop' if concept else 'middle' if ident.startswith('horizon_') else 'ground'
    dest = DEST / (ident + ('.png' if role == 'middle' else '.webp'))
    if role == 'middle':
        shutil.copyfile(src, dest)
        operation = 'Byte-identical runtime RGBA; supplier wrap seams retained.'
    else:
        with Image.open(src) as im:
            im.load()
            if concept:
                im.thumbnail((1024, 1024), Image.Resampling.LANCZOS)
            im.save(dest, 'WEBP', lossless=concept, quality=92, method=6)
        operation = '1024px lossless-WebP decorative concept cutout, NOT a mesh.' if concept else '2048px runtime base-color to quality92 WebP; no PBR synthesis.'
    record(src, dest, ident, operation)
    catalog[ident] = dict(role=role, src='/' + dest.relative_to(PUBLIC).as_posix(), tags=a['tags'] + (['decorative-cutout-not-mesh'] if concept else []), wrapS=role != 'prop', wrapT=role == 'ground')
    if concept:
        with Image.open(dest) as im:
            # Same alpha cutoff as the rendered/shadow silhouette. Keep artwork
            # bytes intact; place its opaque base on the floor, not its padding.
            bounds = im.getchannel('A').point(lambda a: 255 if a >= 26 else 0).getbbox()
            catalog[ident]['groundV'] = bounds[3] / im.height

atlases = {}
for a in fx['atlases']:
    ident = a['id']
    src = VISUAL / 'fx' / a['paths']['rgba']
    assert sha(src) == a['file_hashes']['rgba'], ident
    dest = DEST / (ident + '.png')
    shutil.copyfile(src, dest)
    record(src, dest, ident, 'Byte-identical RGBA atlas. No duplicate alpha mask. Half-texel UVs; mipmaps disabled.')
    catalog[ident] = dict(role='fx', src='/' + dest.relative_to(PUBLIC).as_posix(), tags=[a['type'], 'animated-atlas'], wrapS=False, wrapT=False)
    atlases[ident] = dict(fps=a['fps'], width=a['w'], height=a['h'], blend=a['blend'], pivot=a['pivot'], frames=[dict(offset=f['uv_offset'], repeat=f['uv_repeat']) for f in a['frames']])

for src in sorted(AUDIO.glob('*/ogg/*.ogg')):
    dest = PUBLIC / 'audio/environments' / src.name
    assert not dest.exists() or sha(dest) == sha(src), f'Refuse unrelated overwrite: {dest}'
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dest)
    record(src, dest, src.stem, 'Byte-identical supplied OGG Vorbis runtime; listening acceptance pending.')

assert len(catalog) == 32 and len(atlases) == 8 and len(assets) == 58
(DEST / 'manifest.json').write_text(json.dumps(dict(schema='aiw.environment-expansion/1', assets=assets,
    sourceInventory=inventory, limitations=['Ten props are transparent concept cutouts, not GLB meshes.', 'Supplier horizon/ground seams retained; no native 4K claim.', 'Image model/license metadata not exposed; audio ElevenLabs plan rights and listening acceptance unverified. No public distribution authorized.', 'RGBA atlases include all ten FX sources. Separate masks, individual frames, masters, native variations and preview vendor scripts are accounted for but not duplicated in runtime.']), indent=2)+'\n')
(REPO / 'packages/world-schema/src/environment-expansion.ts').write_text('/** Generated by import-environment-expansion.py; supplied cutouts are not meshes. */\nexport const ENVIRONMENT_EXPANSION = '+json.dumps(catalog,indent=2)+' as const;\nexport const ENVIRONMENT_FX = '+json.dumps(atlases,indent=2)+' as const;\n')
print(json.dumps(dict(inventoried=len(inventory), runtimeAssets=len(assets), visualCatalog=len(catalog), atlases=len(atlases), audio=len(assets)-len(catalog), output=str(DEST)), indent=2))
