"""Offline intake of supplied custom-library-v1; never executes supplier scripts."""
import argparse
import hashlib
import json
from collections import Counter
from pathlib import Path
from PIL import Image, ImageChops

parser = argparse.ArgumentParser()
parser.add_argument('source', type=Path)
args = parser.parse_args()
root = Path(__file__).resolve().parents[2]
source = args.source.resolve()
manifest = json.loads((source / 'manifest.json').read_text())
assets = manifest['assets']
assert len(assets) == len({a['id'] for a in assets}) == 48
expected = {'ground':14, 'masks':6, 'sky':6, 'horizons':6, 'celestial':8, 'atmosphere':8}
assert Counter(a['category'] for a in assets) == expected
out = root / 'apps/web/public/assets/environments/library-v1'
out.mkdir(parents=True, exist_ok=True)
roles = {'ground':'ground','masks':'mask','sky':'background','horizons':'middle','celestial':'celestial','atmosphere':'foreground'}
catalog = {}
verified = []
for a in assets:
    name = a['id']; assert name.replace('_','').isalnum()
    variants = {}
    for kind, variant in a['variants'].items():
        p = (source / variant['path']).resolve(); assert p.is_relative_to(source)
        with Image.open(p) as image:
            image.load()
            assert image.format == 'PNG' and list(image.size) == variant['dimensions']
            alpha = image.getchannel('A').getextrema() if 'A' in image.getbands() else None
            if kind in ('master','runtime') and a['category'] in ('horizons','celestial','atmosphere'):
                assert alpha and alpha[0] == 0 and alpha[1] > 0
            variants[kind] = {'path': variant['path'], 'sha256': hashlib.sha256(p.read_bytes()).hexdigest(), 'dimensions': list(image.size), 'mode': image.mode, 'alphaRange': alpha}
    p = source / a['variants']['runtime']['path']
    with Image.open(p) as im:
        im.load()
        # Lossless WebP preserves authored wrap edges and straight alpha.
        im.save(out / f'{name}.webp', 'WEBP', lossless=True, method=6)
        wrap = a['intended']
        edges = {}
        if wrap['wrap_x']:
            edges['x'] = max(v[1] for v in ImageChops.difference(im.crop((0,0,1,im.height)), im.crop((im.width-1,0,im.width,im.height))).convert('RGBA').getextrema())
        if wrap['wrap_y']:
            edges['y'] = max(v[1] for v in ImageChops.difference(im.crop((0,0,im.width,1)), im.crop((0,im.height-1,im.width,im.height))).convert('RGBA').getextrema())
        # Ignore synthetic opaque alpha on RGB differences.
        for axis in edges:
            if 'A' not in im.getbands():
                first,last = (im.crop((0,0,1,im.height)),im.crop((im.width-1,0,im.width,im.height))) if axis=='x' else (im.crop((0,0,im.width,1)),im.crop((0,im.height-1,im.width,im.height)))
                edges[axis] = max(v[1] for v in ImageChops.difference(first,last).convert('RGB').getextrema())
        assert all(v == 0 for v in edges.values()), (name,edges)
    dest = out / f'{name}.webp'
    with Image.open(dest) as encoded:
        encoded.load(); assert encoded.size == tuple(a['variants']['runtime']['dimensions'])
    catalog[name] = {'role':roles[a['category']], 'src':f'/assets/environments/library-v1/{name}.webp','tags':a['semantic_tags'],'wrapS':wrap['wrap_x'],'wrapT':wrap['wrap_y'],'description':a['description']}
    verified.append({'id':name,'category':a['category'],'variants':variants,'generation':a['generation'],'transformations':a['transformations'],'limitations':a['limitations'],'wrapEdgeMax':edges,'output':{'file':dest.name,'bytes':dest.stat().st_size,'sha256':hashlib.sha256(dest.read_bytes()).hexdigest()}})
(out / 'manifest.json').write_text(json.dumps({'schema':'aiw.environment-library/1','assetCount':len(verified),'assets':verified,'limitations':'Generated masters are upscaled; alpha/edge measurements and contact-sheet review do not certify in-World visuals or seamless projection.'},indent=2)+'\n')
(root / 'packages/world-schema/src/environment-library.ts').write_text('/** Generated by import-environment-library.py from the verified supplied inventory. */\nexport const ENVIRONMENT_LIBRARY = '+json.dumps(catalog,indent=2)+' as const;\n')
print(json.dumps({'verified':len(verified),'categories':expected,'outputBytes':sum(a['output']['bytes'] for a in verified),'output':str(out)}))
