/** Generated by import-environment-expansion.py; supplied cutouts are not meshes. */
export const ENVIRONMENT_EXPANSION = {
  horizon_alpine_snow: {
    role: "middle",
    src: "/assets/environments/expansion-v2/horizon_alpine_snow.png",
    tags: ["alpine", "snow", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: false,
  },
  horizon_glacial_ridges: {
    role: "middle",
    src: "/assets/environments/expansion-v2/horizon_glacial_ridges.png",
    tags: ["glacial", "ridges", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: false,
  },
  horizon_desert_mesas: {
    role: "middle",
    src: "/assets/environments/expansion-v2/horizon_desert_mesas.png",
    tags: ["desert", "mesas", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: false,
  },
  horizon_basalt_volcanic: {
    role: "middle",
    src: "/assets/environments/expansion-v2/horizon_basalt_volcanic.png",
    tags: ["basalt", "volcanic", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: false,
  },
  horizon_temperate_forest: {
    role: "middle",
    src: "/assets/environments/expansion-v2/horizon_temperate_forest.png",
    tags: ["temperate", "forest", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: false,
  },
  horizon_boreal_forest: {
    role: "middle",
    src: "/assets/environments/expansion-v2/horizon_boreal_forest.png",
    tags: ["boreal", "forest", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: false,
  },
  horizon_coastal_cliffs: {
    role: "middle",
    src: "/assets/environments/expansion-v2/horizon_coastal_cliffs.png",
    tags: ["coastal", "cliffs", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: false,
  },
  horizon_alien_crystal_ridges: {
    role: "middle",
    src: "/assets/environments/expansion-v2/horizon_alien_crystal_ridges.png",
    tags: [
      "alien",
      "crystal",
      "ridges",
      "naturalistic",
      "environment-expansion",
    ],
    wrapS: true,
    wrapT: false,
  },
  ground_forest_leaf_litter: {
    role: "ground",
    src: "/assets/environments/expansion-v2/ground_forest_leaf_litter.webp",
    tags: ["forest", "leaf", "litter", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: true,
  },
  ground_tundra_lichen: {
    role: "ground",
    src: "/assets/environments/expansion-v2/ground_tundra_lichen.webp",
    tags: ["tundra", "lichen", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: true,
  },
  ground_coastal_pebbles: {
    role: "ground",
    src: "/assets/environments/expansion-v2/ground_coastal_pebbles.webp",
    tags: ["coastal", "pebbles", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: true,
  },
  ground_weathered_sandstone: {
    role: "ground",
    src: "/assets/environments/expansion-v2/ground_weathered_sandstone.webp",
    tags: ["weathered", "sandstone", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: true,
  },
  ground_salt_flat: {
    role: "ground",
    src: "/assets/environments/expansion-v2/ground_salt_flat.webp",
    tags: ["salt", "flat", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: true,
  },
  ground_wet_marsh_soil: {
    role: "ground",
    src: "/assets/environments/expansion-v2/ground_wet_marsh_soil.webp",
    tags: ["wet", "marsh", "soil", "naturalistic", "environment-expansion"],
    wrapS: true,
    wrapT: true,
  },
  prop_ice_slab: {
    role: "prop",
    groundV: 0.8310546875,
    src: "/assets/environments/expansion-v2/prop_ice_slab.webp",
    tags: [
      "ice",
      "slab",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  prop_ice_shard_cluster: {
    role: "prop",
    groundV: 0.9716796875,
    src: "/assets/environments/expansion-v2/prop_ice_shard_cluster.webp",
    tags: [
      "ice",
      "shard",
      "cluster",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  prop_frosted_stone: {
    role: "prop",
    groundV: 0.8564453125,
    src: "/assets/environments/expansion-v2/prop_frosted_stone.webp",
    tags: [
      "frosted",
      "stone",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  prop_basalt_boulder: {
    role: "prop",
    groundV: 0.927734375,
    src: "/assets/environments/expansion-v2/prop_basalt_boulder.webp",
    tags: [
      "basalt",
      "boulder",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  prop_sandstone_boulder: {
    role: "prop",
    groundV: 0.943359375,
    src: "/assets/environments/expansion-v2/prop_sandstone_boulder.webp",
    tags: [
      "sandstone",
      "boulder",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  prop_crystal_cluster: {
    role: "prop",
    groundV: 0.974609375,
    src: "/assets/environments/expansion-v2/prop_crystal_cluster.webp",
    tags: [
      "crystal",
      "cluster",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  prop_fern_clump: {
    role: "prop",
    groundV: 0.9521484375,
    src: "/assets/environments/expansion-v2/prop_fern_clump.webp",
    tags: [
      "fern",
      "clump",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  prop_low_shrub: {
    role: "prop",
    groundV: 0.9189453125,
    src: "/assets/environments/expansion-v2/prop_low_shrub.webp",
    tags: [
      "low",
      "shrub",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  prop_reed_clump: {
    role: "prop",
    groundV: 0.982421875,
    src: "/assets/environments/expansion-v2/prop_reed_clump.webp",
    tags: [
      "reed",
      "clump",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  prop_driftwood: {
    role: "prop",
    groundV: 0.6533203125,
    src: "/assets/environments/expansion-v2/prop_driftwood.webp",
    tags: [
      "driftwood",
      "naturalistic",
      "environment-expansion",
      "decorative-cutout-not-mesh",
    ],
    wrapS: false,
    wrapT: false,
  },
  fx_lightning_strike: {
    role: "fx",
    src: "/assets/environments/expansion-v2/fx_lightning_strike.png",
    tags: ["bolt", "animated-atlas"],
    wrapS: false,
    wrapT: false,
  },
  fx_lightning_arc: {
    role: "fx",
    src: "/assets/environments/expansion-v2/fx_lightning_arc.png",
    tags: ["arc", "animated-atlas"],
    wrapS: false,
    wrapT: false,
  },
  fx_impact_dust: {
    role: "fx",
    src: "/assets/environments/expansion-v2/fx_impact_dust.png",
    tags: ["dust", "animated-atlas"],
    wrapS: false,
    wrapT: false,
  },
  fx_impact_flash: {
    role: "fx",
    src: "/assets/environments/expansion-v2/fx_impact_flash.png",
    tags: ["flash", "animated-atlas"],
    wrapS: false,
    wrapT: false,
  },
  fx_impact_ground_arcs: {
    role: "fx",
    src: "/assets/environments/expansion-v2/fx_impact_ground_arcs.png",
    tags: ["ground_arcs", "animated-atlas"],
    wrapS: false,
    wrapT: false,
  },
  fx_impact_scorch: {
    role: "fx",
    src: "/assets/environments/expansion-v2/fx_impact_scorch.png",
    tags: ["scorch", "animated-atlas"],
    wrapS: false,
    wrapT: false,
  },
  fx_impact_shockwave: {
    role: "fx",
    src: "/assets/environments/expansion-v2/fx_impact_shockwave.png",
    tags: ["shockwave", "animated-atlas"],
    wrapS: false,
    wrapT: false,
  },
  fx_impact_sparks: {
    role: "fx",
    src: "/assets/environments/expansion-v2/fx_impact_sparks.png",
    tags: ["sparks", "animated-atlas"],
    wrapS: false,
    wrapT: false,
  },
} as const;
export const ENVIRONMENT_FX = {
  fx_lightning_strike: {
    fps: 40,
    width: 256,
    height: 768,
    blend: "additive",
    pivot: [0.5, 0.95],
    frames: [
      {
        offset: [0.00048828125, 0.7501627604166666],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.25048828125, 0.7501627604166666],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.50048828125, 0.7501627604166666],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.75048828125, 0.7501627604166666],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.00048828125, 0.5001627604166667],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.25048828125, 0.5001627604166667],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.50048828125, 0.5001627604166667],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.75048828125, 0.5001627604166667],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.00048828125, 0.25016276041666663],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.25048828125, 0.25016276041666663],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.50048828125, 0.25016276041666663],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.75048828125, 0.25016276041666663],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.00048828125, 0.00016276041666662966],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.25048828125, 0.00016276041666662966],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.50048828125, 0.00016276041666662966],
        repeat: [0.2490234375, 0.24967447916666666],
      },
      {
        offset: [0.75048828125, 0.00016276041666662966],
        repeat: [0.2490234375, 0.24967447916666666],
      },
    ],
  },
  fx_lightning_arc: {
    fps: 40,
    width: 768,
    height: 256,
    blend: "additive",
    pivot: [0.5, 0.5],
    frames: [
      {
        offset: [0.00016276041666666666, 0.75048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.2501627604166667, 0.75048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.5001627604166666, 0.75048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.7501627604166666, 0.75048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.00016276041666666666, 0.50048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.2501627604166667, 0.50048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.5001627604166666, 0.50048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.7501627604166666, 0.50048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.00016276041666666666, 0.25048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.2501627604166667, 0.25048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.5001627604166666, 0.25048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.7501627604166666, 0.25048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.00016276041666666666, 0.00048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.2501627604166667, 0.00048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.5001627604166666, 0.00048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
      {
        offset: [0.7501627604166666, 0.00048828125],
        repeat: [0.24967447916666666, 0.2490234375],
      },
    ],
  },
  fx_impact_dust: {
    fps: 16,
    width: 512,
    height: 512,
    blend: "normal",
    pivot: [0.5, 0.91],
    frames: [
      {
        offset: [0.000244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
    ],
  },
  fx_impact_flash: {
    fps: 32,
    width: 512,
    height: 512,
    blend: "additive",
    pivot: [0.5, 0.5],
    frames: [
      {
        offset: [0.000244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
    ],
  },
  fx_impact_ground_arcs: {
    fps: 32,
    width: 512,
    height: 512,
    blend: "additive",
    pivot: [0.5, 0.5],
    frames: [
      {
        offset: [0.000244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
    ],
  },
  fx_impact_scorch: {
    fps: 4,
    width: 512,
    height: 512,
    blend: "normal",
    pivot: [0.5, 0.5],
    frames: [
      {
        offset: [0.000244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
    ],
  },
  fx_impact_shockwave: {
    fps: 32,
    width: 512,
    height: 512,
    blend: "additive",
    pivot: [0.5, 0.5],
    frames: [
      {
        offset: [0.000244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
    ],
  },
  fx_impact_sparks: {
    fps: 32,
    width: 512,
    height: 512,
    blend: "additive",
    pivot: [0.51, 0.9],
    frames: [
      {
        offset: [0.000244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.750244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.500244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.250244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.000244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.250244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.500244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
      {
        offset: [0.750244140625, 0.000244140625],
        repeat: [0.24951171875, 0.24951171875],
      },
    ],
  },
} as const;
