/** Small startup-safe audio identifiers; no visual-library dependency. */
export const ENVIRONMENT_AMBIENCE = [
  "blue-sky-sand-grass",
  "mars-swirling-gases",
  "alien-planet-loop",
  "birds-loop",
  "coding-beeps-chirps-loop",
  "rain-loop",
  "thunder-lightning-loop",
  "wind-loop",
  "crystal_cavern_drips_loop",
  "desert_soft_sand_loop",
  "forest_canopy_day_loop",
  "forest_floor_damp_loop",
  "marsh_evening_loop",
  "night_meadow_insects_loop",
  "ocean_gentle_shore_loop",
  "ocean_rocky_cove_loop",
  "polar_ice_creaks_loop",
  "rain_heavy_environment_loop",
  "rain_light_environment_loop",
  "snowfield_sheltered_wind_loop",
  "stream_shallow_stones_loop",
  "thunder_distant_environment_loop",
  "waterfall_distant_soft_loop",
] as const;
export const ENVIRONMENT_EVENT_AUDIO = [
  "lightning_impact_sand_scorch",
  "lightning_impact_stone_sizzle",
  "lightning_impact_wet_earth",
  "lightning_scorch_dry_sizzle",
  "lightning_scorch_steam_hiss",
  "lightning_strike_air_tearing",
  "lightning_strike_branching_snap",
  "lightning_strike_dry_crack",
  "thunder_far_horizon_rumble",
  "thunder_mid_distance_rolling",
  "thunder_near_crack_roll",
] as const;
export type EnvironmentAmbience = (typeof ENVIRONMENT_AMBIENCE)[number];
