// Generated by tooling/scripts/generate-world-tsl.mjs from tooling/world-shaders.glsl.
// Three.js Transpiler r186

import {
  vec2,
  If,
  sin,
  mul,
  Fn,
  vec4,
  max,
  smoothstep,
  add,
  select,
  floor,
  vec3,
  dot,
  fract,
  length,
  abs,
  sub,
  pow,
  mix,
  min,
  step,
  normalize,
  fwidth,
  property,
  mod,
  cos,
  mat2,
  Discard,
  float,
  exp,
  clamp,
  sqrt,
} from "three/tsl";

export const aiwStreamingUv = /*@__PURE__*/ Fn(
  ([skyUv, aiwSkyTime, aiwSkyLayer]) => {
    const t = aiwSkyTime.toVar();

    If(aiwSkyLayer.lessThan(0.5), () => {
      // Sphere V increases toward the zenith: positive sampling offset falls down.

      return skyUv.add(vec2(0.0, t.mul(0.055)));
    });

    If(aiwSkyLayer.lessThan(1.5), () => {
      // Rising, folding aurora curtains: streaming plus smooth lateral ripples.

      const flow = skyUv.add(vec2(t.mul(0.006), t.negate().mul(0.022))).toVar();
      flow.x.addAssign(
        mul(0.045, sin(skyUv.y.mul(6.283185).add(t.mul(0.32)))).add(
          mul(0.018, sin(skyUv.y.mul(12.56637).sub(t.mul(0.21)))),
        ),
      );
      flow.y.addAssign(mul(0.035, sin(skyUv.x.mul(6.283185).add(t.mul(0.24)))));

      return flow;
    });

    // Foreground clouds cross the curtains on an independent, slower current.

    const flow = skyUv.add(vec2(t.negate().mul(0.009), t.mul(0.008))).toVar();
    flow.x.addAssign(mul(0.03, sin(skyUv.y.mul(6.283185).sub(t.mul(0.17)))));
    flow.y.addAssign(mul(0.025, sin(skyUv.x.mul(12.56637).add(t.mul(0.19)))));

    return flow;
  },
  { skyUv: "vec2", aiwSkyTime: "float", aiwSkyLayer: "float", return: "vec2" },
);

export const codeSky = /*@__PURE__*/ Fn(
  ([map, vMapUv, aiwSkyTime, aiwSkyLayer]) => {
    const skyColor = vec4(1.0).toVar();
    const skyArt = map
      .sample(aiwStreamingUv(vMapUv, aiwSkyTime, aiwSkyLayer))
      .toVar();
    const light = max(skyArt.r, max(skyArt.g, skyArt.b)).toVar();

    // Supplied maps are RGB. Remove dark backing, not the luminous glyphColor artwork.

    skyColor.a.mulAssign(skyArt.a.mul(smoothstep(0.003, 0.028, light)));
    const curtain = add(
      0.88,
      mul(0.12, sin(vMapUv.x.mul(6.283185).sub(aiwSkyTime.mul(0.35)))),
    ).toVar();
    const glow = select(
      aiwSkyLayer.lessThan(0.5),
      1.0,
      select(aiwSkyLayer.lessThan(1.5), mul(1.5, curtain), 1.35),
    ).toVar();
    skyColor.rgb.mulAssign(skyArt.rgb.mul(glow));

    return skyColor;
  },
);

export const rewriteSurface = /*@__PURE__*/ Fn(
  ([
    original,
    vWorldSurface,
    vEnvironmentRewriteUv,
    environmentRewriteCode,
    environmentRewriteTime,
    environmentRewriteStrength,
  ]) => {
    const result = original.toVar();

    If(environmentRewriteStrength.greaterThan(0.001), () => {
      const p = vWorldSurface.toVar();
      const cell = floor(p.mul(0.9)).toVar();
      const seed = fract(
        sin(dot(cell, vec3(127.1, 311.7, 74.7))).mul(43758.5453),
      ).toVar();
      const wave = add(
        0.5,
        mul(
          0.5,
          sin(
            environmentRewriteTime
              .mul(3.0)
              .add(length(p.xz).mul(0.32))
              .add(p.y.mul(0.12)),
          ),
        ),
      ).toVar();
      const circuit = pow(
        max(
          0.0,
          sub(
            1.0,
            abs(
              sin(
                p.x
                  .mul(2.8)
                  .add(p.z.mul(1.9))
                  .add(environmentRewriteTime.mul(1.8)),
              ),
            ),
          ),
        ),
        26.0,
      ).toVar();
      const spark = smoothstep(0.975, 1.0, seed).mul(pow(wave, 8.0)).toVar();
      const patches = smoothstep(0.35, 0.85, seed).mul(wave).toVar();
      const rewriteColor = mix(
        result.rgb.mul(0.35),
        vec3(0.25, 0.85, 1.0),
        max(circuit, spark),
      ).toVar();
      result.rgb.assign(
        mix(
          result.rgb,
          rewriteColor,
          environmentRewriteStrength.mul(
            min(0.9, patches.mul(0.55).add(circuit.mul(0.55)).add(spark)),
          ),
        ),
      );

      // Independently staggered small surface patches, never a whole-screen strobe.

      const surfaceUv = vEnvironmentRewriteUv.mul(vec2(18.0, 10.0)).toVar();
      const tile = floor(surfaceUv).toVar();
      const tick = floor(environmentRewriteTime.mul(11.0)).toVar();
      const burst = fract(
        sin(dot(tile, vec2(41.7, 113.1)).add(tick.mul(19.19))).mul(43758.5453),
      ).toVar();
      const edge = smoothstep(vec2(0.0), vec2(0.08), fract(surfaceUv))
        .mul(sub(1.0, smoothstep(vec2(0.92), vec2(1.0), fract(surfaceUv))))
        .toVar();
      const flash = step(0.76, burst)
        .mul(edge.x)
        .mul(edge.y)
        .mul(environmentRewriteStrength)
        .toVar();

      // Complementary cells disappear into black while other cells expose streaming glyphColor.
      // The disjoint thresholds prevent an erased patch from also flashing cyan.

      const erase = sub(1.0, step(0.24, burst))
        .mul(edge.x)
        .mul(edge.y)
        .mul(min(1.0, environmentRewriteStrength.mul(1.5)))
        .toVar();
      result.rgb.assign(mix(result.rgb, vec3(0.0), erase));

      // Stream the supplied terminal-rain artwork through momentarily exposed sections.

      const codeUv = vEnvironmentRewriteUv
        .mul(vec2(3.0, 2.0))
        .add(vec2(0.0, environmentRewriteTime.mul(0.42)))
        .toVar();
      const glyphColor = environmentRewriteCode.sample(codeUv).rgb.toVar();
      const glyph = smoothstep(
        0.025,
        0.32,
        max(glyphColor.r, max(glyphColor.g, glyphColor.b)),
      ).toVar();
      const exposedCode = mix(
        vec3(0.005, 0.035, 0.06),
        vec3(0.3, 0.92, 1.0),
        glyph,
      ).toVar();
      result.rgb.assign(mix(result.rgb, exposedCode, flash.mul(0.95)));
    });

    return result;
  },
);

export const starHash = /*@__PURE__*/ Fn(
  ([p]) => {
    return fract(sin(dot(p, vec3(127.1, 311.7, 74.7))).mul(43758.5453));
  },
  { p: "vec3", return: "float" },
);

export const starfield = /*@__PURE__*/ Fn(
  ([vSkyDirection, density]) => {
    const d = normalize(vSkyDirection).toVar();
    const p = d.mul(370.0).toVar();
    const cell = floor(p).toVar();
    const h = starHash(cell).toVar();
    const center = cell
      .add(vec3(0.2))
      .add(
        mul(
          0.6,
          vec3(
            starHash(cell.add(1.0)),
            starHash(cell.add(2.0)),
            starHash(cell.add(3.0)),
          ),
        ),
      )
      .toVar();
    const distanceToStar = length(p.sub(center)).toVar();
    const radius = mix(0.035, 0.1, starHash(cell.add(4.0))).toVar();
    const aa = max(length(fwidth(p)).mul(0.5), 0.025).toVar();
    const light = step(sub(1.0, density), h)
      .mul(sub(1.0, smoothstep(radius, radius.add(aa), distanceToStar)))
      .toVar();

    return vec4(
      vec3(0.002, 0.004, 0.012).add(vec3(0.82, 0.9, 1.0).mul(light)),
      1.0,
    );
  },
  { vSkyDirection: "vec3", density: "float", return: "vec4" },
);

export const weatherPosition = /*@__PURE__*/ Fn(
  ([position, time, wind, kind]) => {
    const seed = property("float");
    seed.assign(
      fract(sin(dot(position.xz, vec2(127.1, 311.7))).mul(43758.5453)),
    );
    const p = position.toVar();
    const fall = select(
      kind.lessThan(1.5),
      14.0,
      select(kind.lessThan(2.5), 1.4, select(kind.lessThan(3.5), 0.7, 0.3)),
    ).toVar();

    If(kind.greaterThan(3.5).and(kind.lessThan(4.5)), () => {
      fall.assign(-0.4);
    });

    If(kind.greaterThan(7.5), () => {
      fall.assign(-1.0);
    });

    p.y.assign(mod(position.y.sub(time.mul(fall)), 24.0));
    p.x.assign(
      mod(
        position.x
          .add(time.mul(add(0.4, wind.mul(7.0))))
          .add(sin(time.mul(0.6).add(seed.mul(25.0))).mul(add(0.4, wind))),
        48.0,
      ).sub(24.0),
    );
    p.z.assign(
      mod(
        position.z.add(
          sin(time.mul(0.3).add(seed.mul(13.0))).mul(add(1.0, wind)),
        ),
        48.0,
      ).sub(24.0),
    );

    return p;
  },
  {
    position: "vec3",
    time: "float",
    wind: "float",
    kind: "float",
    return: "vec3",
  },
);

export const weatherColor = /*@__PURE__*/ Fn(
  ([pointUv, kind, time, wind, seed]) => {
    const p = pointUv.sub(0.5).toVar();
    const a = property("float");
    const color = property("vec3");

    If(kind.lessThan(1.5), () => {
      p.x.addAssign(p.y.mul(wind).mul(0.5));
      a.assign(
        sub(1.0, smoothstep(0.025, 0.09, abs(p.x))).mul(
          sub(1.0, smoothstep(0.2, 0.5, abs(p.y))),
        ),
      );
      color.assign(vec3(0.65, 0.82, 0.94));
      a.mulAssign(0.55);
    })
      .ElseIf(kind.lessThan(2.5), () => {
        a.assign(sub(1.0, smoothstep(0.15, 0.48, length(p))));
        color.assign(vec3(0.9, 0.96, 1.0));
      })
      .ElseIf(kind.lessThan(3.5), () => {
        a.assign(sub(1.0, smoothstep(0.1, 0.48, length(p))));
        color.assign(vec3(0.52, 0.48, 0.45));
        a.mulAssign(0.55);
      })
      .ElseIf(kind.lessThan(4.5), () => {
        a.assign(
          max(
            pow(max(0.0, sub(1.0, length(p).mul(2.0))), 2.0),
            mul(
              0.65,
              sub(1.0, smoothstep(0.015, 0.04, min(abs(p.x), abs(p.y)))),
            ).mul(sub(1.0, smoothstep(0.15, 0.5, length(p)))),
          ),
        );
        color.assign(mix(vec3(0.5, 0.75, 1.0), vec3(1.0, 0.85, 0.45), seed));
        a.mulAssign(add(0.6, mul(0.4, sin(time.add(seed.mul(20.0))))));
      })
      .ElseIf(kind.lessThan(5.5), () => {
        a.assign(
          sub(
            1.0,
            smoothstep(
              0.01,
              0.04,
              abs(p.y.add(sin(p.x.mul(5.0).add(time)).mul(0.08))),
            ),
          ).mul(sub(1.0, smoothstep(0.1, 0.5, abs(p.x)))),
        );
        color.assign(vec3(0.75, 0.84, 0.85));
        a.mulAssign(0.23);
      })
      .ElseIf(kind.lessThan(6.5), () => {
        const angle = seed.mul(6.28).add(time).toVar();
        p.assign(
          mat2(cos(angle), sin(angle).negate(), sin(angle), cos(angle)).mul(p),
        );
        a.assign(
          sub(1.0, smoothstep(0.36, 0.48, length(p.mul(vec2(1.0, 2.4))))),
        );
        color.assign(mix(vec3(0.28, 0.4, 0.09), vec3(0.85, 0.37, 0.08), seed));
      })
      .ElseIf(kind.lessThan(7.5), () => {
        a.assign(sub(1.0, smoothstep(0.05, 0.48, length(p))));
        color.assign(vec3(0.76, 0.54, 0.3));
        a.mulAssign(0.35);
      })
      .Else(() => {
        a.assign(pow(max(0.0, sub(1.0, length(p).mul(2.0))), 2.0));
        color.assign(vec3(1.0, add(0.33, seed.mul(0.35)), 0.05));
      });

    If(a.lessThan(0.01), () => {
      Discard();
    });

    return vec4(color, a);
  },
  {
    pointUv: "vec2",
    kind: "float",
    time: "float",
    wind: "float",
    seed: "float",
    return: "vec4",
  },
);

export const terminalRain = /*@__PURE__*/ Fn(
  ([
    rainMap,
    rainUv,
    rainTime,
    rainHeight,
    rainReach,
    rainSpark,
    rainVisible,
    rainPulse,
    rainStrength,
    rainColor,
  ]) => {
    If(rainUv.y.greaterThan(rainReach).or(rainVisible.lessThan(0.001)), () => {
      Discard();
    });

    // Positive V sample motion makes the visible glyphs travel DOWN.

    const glyphColor = rainMap
      .sample(vec2(rainUv.x, rainUv.y.mul(rainHeight).div(18.0).add(rainTime)))
      .rgb.toVar();
    const ink = max(glyphColor.r, max(glyphColor.g, glyphColor.b)).toVar();
    const glyph = smoothstep(0.008, 0.055, ink).toVar();

    // Broad packets move at four world units/second, not hundreds of
    // units/second across the entire sky height. Six-second eased envelope.

    const pulse = float(0.0).toVar();

    If(rainStrength.greaterThan(0.0), () => {
      const packet = mod(
        rainUv.y.mul(rainHeight).add(rainPulse.mul(24.0)),
        36.0,
      ).toVar();
      pulse.assign(
        exp(pow(packet.sub(18.0).div(5.0), 2.0).negate()).mul(rainStrength),
      );
    });

    const tint = mix(vec3(0.12, 0.55, 0.76), rainColor, pulse).toVar();
    const root = smoothstep(0.0, 0.003, rainUv.y).toVar();
    const spark = exp(
      pow(rainUv.y.sub(rainReach).mul(rainHeight).div(3.0), 2.0).negate(),
    )
      .mul(rainSpark)
      .toVar();

    return vec4(
      tint.mul(add(1.0, pulse.mul(0.35))).add(vec3(0.35, 0.7, 1.0).mul(spark)),
      max(glyph.mul(root).mul(add(0.65, pulse.mul(0.15))), spark.mul(0.6)).mul(
        rainVisible,
      ),
    );
  },
);

export const arrival = /*@__PURE__*/ Fn(
  ([
    original,
    aiwArrivalPosition,
    aiwArrivalProgress,
    aiwArrivalTime,
    aiwArrivalFloor,
    aiwArrivalHeight,
    aiwArrivalRain,
  ]) => {
    // Small spatial cells assemble upward with staggered, stable thresholds.

    const cell = floor(aiwArrivalPosition.mul(18.0)).toVar();
    const noise = fract(
      sin(dot(cell, vec3(12.9898, 78.233, 37.719))).mul(43758.5453),
    ).toVar();
    const height = clamp(
      aiwArrivalPosition.y.sub(aiwArrivalFloor).div(aiwArrivalHeight),
      0.0,
      1.0,
    ).toVar();
    const threshold = height.mul(0.72).add(noise.mul(0.28)).toVar();

    If(threshold.greaterThan(aiwArrivalProgress), () => {
      Discard();
    });

    const edge = sub(
      1.0,
      smoothstep(0.0, 0.2, aiwArrivalProgress.sub(threshold)),
    ).toVar();
    const rainUv = vec2(
      aiwArrivalPosition.x.mul(0.55).add(aiwArrivalPosition.z.mul(0.3)),
      aiwArrivalPosition.y.mul(0.55).add(aiwArrivalTime.mul(0.24)),
    ).toVar();
    const glyphColor = aiwArrivalRain.sample(rainUv).rgb.toVar();
    const outgoingLight = mix(
      original.rgb,
      glyphColor.mul(3.5).add(vec3(0.03, 0.32, 0.46)),
      edge,
    ).toVar();

    return vec4(outgoingLight, original.a);
  },
);

export const hash = /*@__PURE__*/ Fn(
  ([p]) => {
    return fract(sin(dot(p, vec2(127.1, 311.7))).mul(43758.5453));
  },
  { p: "vec2", return: "float" },
);

export const noise = /*@__PURE__*/ Fn(
  ([p]) => {
    const i = floor(p),
      f = fract(p).toVar().toVar();
    f.assign(f.mul(f).mul(sub(3.0, mul(2.0, f))));

    return mix(
      mix(hash(i), hash(i.add(vec2(1, 0))), f.x),
      mix(hash(i.add(vec2(0, 1))), hash(i.add(vec2(1))), f.x),
      f.y,
    );
  },
  { p: "vec2", return: "float" },
);

export const baseFog = /*@__PURE__*/ Fn(
  ([start, worldPosition, surface, center, extent, time, coverage]) => {
    If(coverage.lessThan(0.01), () => {
      Discard();
    });

    const direction = normalize(worldPosition.sub(start)).toVar();
    const surfaceDistance = max(
      0.0,
      dot(surface.sub(start), direction),
    ).toVar();

    // Analytic ray/ellipsoid bounds and continuous density integration.
    // No horizontal surfaces, marching steps or view-dependent layer count.

    const origin = start.sub(center).div(extent).toVar();
    const ray = direction.div(extent).toVar();
    const a = dot(ray, ray),
      b = dot(origin, ray),
      c = dot(origin, origin).sub(1.0).toVar().toVar().toVar();
    const discriminant = b.mul(b).sub(a.mul(c)).toVar();

    If(discriminant.lessThanEqual(0.0), () => {
      Discard();
    });

    const root = sqrt(discriminant).toVar();
    const entry = max(0.0, b.negate().sub(root).div(a)).toVar();
    const exit = min(surfaceDistance, b.negate().add(root).div(a)).toVar();

    If(exit.lessThanEqual(entry), () => {
      Discard();
    });

    const halfChord = root.div(a).toVar();
    const peak = discriminant.div(a).toVar();
    const u = clamp(
      vec2(entry, exit).add(b.div(a)).div(halfChord),
      -1.0,
      1.0,
    ).toVar();

    // Integral of (1-u*u)^2: u - 2*u^3/3 + u^5/5.

    const integral = u
      .sub(
        u
          .mul(u)
          .mul(u)
          .mul(2.0 / 3.0),
      )
      .add(u.mul(u).mul(u).mul(u).mul(u).div(5.0))
      .toVar();
    const midpoint = start.add(direction.mul(entry.add(exit)).mul(0.5)).toVar();
    const wisps = add(
      0.5,
      mul(
        0.5,
        noise(
          midpoint.xz
            .mul(1.1)
            .add(vec2(time.mul(0.07), time.negate().mul(0.035)))
            .add(midpoint.y.mul(0.4)),
        ),
      ),
    ).toVar();
    const opticalDepth = max(0.0, integral.y.sub(integral.x))
      .mul(halfChord)
      .mul(peak)
      .mul(peak)
      .mul(wisps)
      .mul(0.35)
      .toVar();
    const alpha = sub(1.0, exp(opticalDepth.negate())).toVar();

    return vec4(vec3(0.2, 0.36, 0.43), alpha);
  },
  {
    start: "vec3",
    worldPosition: "vec3",
    surface: "vec3",
    center: "vec3",
    extent: "vec3",
    time: "float",
    coverage: "float",
    return: "vec4",
  },
);
